In [39]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
#memanggil data yang dibutuhkan
df=pd.read_csv('academic.csv')

In [40]:
#menampilkan tabel awal (default 5 data)
df.head()

,ID,Class,Gender (X1),Status IMT (X2),Berkacamata (X3),Pernah Sakit (X4),Gangguan Psikis (X5),Aktif Bertanya (X6),Aktif Menjawab (X7),Mengerjakan Tugas (X8),...,Mengulang Materi (X13),Praktek Mandiri (X14),Berdiskusi (X15),Memiliki HP(X16),Memiliki Laptop (X17),Kecukupan Kuota Internet (X18),Dukungan Suasana rumah (X19),PLN (X20),Lokasi (X21),Ketersediaan Sinyal (X22)
0,1,0,P,NORMAL,Tidak,Tidak,Tidak,Ya,Ya,Semua,...,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Tidak,Kadang-kadang,Ya,Pedesaan,Sebagian
1,2,2,L,GEMUK,Ya,Tidak,Tidak,Tidak,Tidak,Semua,...,Kadang-kadang,Kadang-kadang,Tidak,Ya,Ya,Ya,Ya,Ya,Perkotaan,Ya
2,3,2,P,NORMAL,Ya,Tidak,Tidak,Tidak,Tidak,Semua,...,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Ya,Ya,Ya,Perkotaan,Sebagian
3,4,2,P,NORMAL,Tidak,Ya,Tidak,Tidak,Tidak,Semua,...,Kadang-kadang,Ya,Ya,Ya,Ya,Ya,Kadang-kadang,Ya,Perkotaan,Ya
4,5,0,P,NORMAL,Tidak,Ya,Ya,Ya,Ya,Semua,...,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Kadang-kadang,Ya,Ya,Perkotaan,Sebagian

In [41]:
for column in df.columns:
  print(f"Kolom {column}: ", np.sort(df[column].unique()))

Kolom ID:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91]
Kolom Class:  [0 1 2 3]
Kolom Gender (X1):  ['L' 'P']
Kolom Status IMT (X2):  ['GEMUK' 'KURUS' 'NORMAL' 'OBESITAS']
Kolom Berkacamata (X3):  ['Tidak' 'Ya']
Kolom Pernah Sakit (X4):  ['Tidak' 'Ya']
Kolom Gangguan Psikis (X5):  ['Tidak' 'Ya']
Kolom Aktif Bertanya (X6):  ['Tidak' 'Ya']
Kolom Aktif Menjawab (X7):  ['Tidak' 'Ya']
Kolom Mengerjakan Tugas (X8):  ['Sebagian' 'Semua']
Kolom Tertarik Materi (X9):  ['Mungkin' 'Tidak' 'Ya']
Kolom Alokasi Jam Belajar (X10):  [' LEBIH DARI 10 JAM' 'ANTARA 5 - 10 JAM' 'KURANG DARI 5 JAM']
Kolom Memiliki Referensi Tambahan(X11):  ['Ada' 'Tidak Ada']
Kolom Browsing dan Youtube (X12):  ['Tidak' 'Ya']
Kolom Mengulang Materi (X13):  ['Kadang-kadang' 'Ya']
Kolom Praktek Mandiri (X14):  ['Kadang-kadang' 'Ya']
Kolom Berdiskusi (X15):  ['Kadang-kadang' 'Tidak' 'Ya']
Kolom Memiliki HP(X16):  ['Tidak' 'Ya']
Kolom Memiliki Laptop (X17):  ['Tidak' 'Ya']
Kolom Kecukupan Kuota Internet (X18):  ['Kadang-kadang' 'Tidak' 'Ya']
Kolom Dukungan Suasana rumah (X19):  ['Kadang-kadang' 'Tidak' 'Ya']
Kolom PLN (X20):  ['Tidak' 'Ya']
Kolom Lokasi (X21):  ['Pedesaan' 'Perkotaan' 'Pesisir']
Kolom Ketersediaan Sinyal  (X22):  ['Sebagian' 'Tidak' 'Ya']

In [42]:
#Mengubah nama kolom
df.columns = [column.lower() for column in df.columns]
df.rename(columns={'gender (x1)':'x1', 'status imt (x2)' : 'x2', 'berkacamata (x3)' : 'x3',
       'pernah sakit (x4)' : 'x4', 'gangguan psikis (x5)' : 'x5', 'aktif bertanya (x6)' : 'x6',
       'aktif menjawab (x7)' : 'x7', 'mengerjakan tugas (x8)' : 'x8', 'tertarik materi (x9)' : 'x9',
       'alokasi jam belajar (x10)' : 'x10', 'memiliki referensi tambahan(x11)' : 'x11',
       'browsing dan youtube (x12)' : 'x12', 'mengulang materi (x13)' : 'x13',
       'praktek mandiri (x14)': 'x14', 'berdiskusi (x15)': 'x15', 'memiliki hp(x16)': 'x16',
       'memiliki laptop (x17)' : 'x17', 'kecukupan kuota internet (x18)': 'x18',
       'dukungan suasana rumah (x19)': 'x19', 'pln (x20)' : 'x20', 'lokasi (x21)': 'x21',
       'ketersediaan sinyal  (x22)': 'x22'}, inplace=True)
df.head()

,id,class,x1,x2,x3,x4,x5,x6,x7,x8,...,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22
0,1,0,P,NORMAL,Tidak,Tidak,Tidak,Ya,Ya,Semua,...,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Tidak,Kadang-kadang,Ya,Pedesaan,Sebagian
1,2,2,L,GEMUK,Ya,Tidak,Tidak,Tidak,Tidak,Semua,...,Kadang-kadang,Kadang-kadang,Tidak,Ya,Ya,Ya,Ya,Ya,Perkotaan,Ya
2,3,2,P,NORMAL,Ya,Tidak,Tidak,Tidak,Tidak,Semua,...,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Ya,Ya,Ya,Perkotaan,Sebagian
3,4,2,P,NORMAL,Tidak,Ya,Tidak,Tidak,Tidak,Semua,...,Kadang-kadang,Ya,Ya,Ya,Ya,Ya,Kadang-kadang,Ya,Perkotaan,Ya
4,5,0,P,NORMAL,Tidak,Ya,Ya,Ya,Ya,Semua,...,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Kadang-kadang,Ya,Ya,Perkotaan,Sebagian

In [43]:
#membersihkan kolom ID
df = df.drop('id', 1)
df

,class,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22
0,0,P,NORMAL,Tidak,Tidak,Tidak,Ya,Ya,Semua,Mungkin,...,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Tidak,Kadang-kadang,Ya,Pedesaan,Sebagian
1,2,L,GEMUK,Ya,Tidak,Tidak,Tidak,Tidak,Semua,Mungkin,...,Kadang-kadang,Kadang-kadang,Tidak,Ya,Ya,Ya,Ya,Ya,Perkotaan,Ya
2,2,P,NORMAL,Ya,Tidak,Tidak,Tidak,Tidak,Semua,Ya,...,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Ya,Ya,Ya,Perkotaan,Sebagian
3,2,P,NORMAL,Tidak,Ya,Tidak,Tidak,Tidak,Semua,Mungkin,...,Kadang-kadang,Ya,Ya,Ya,Ya,Ya,Kadang-kadang,Ya,Perkotaan,Ya
4,0,P,NORMAL,Tidak,Ya,Ya,Ya,Ya,Semua,Ya,...,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Kadang-kadang,Ya,Ya,Perkotaan,Sebagian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,1,L,NORMAL,Tidak,Tidak,Tidak,Ya,Ya,Semua,Ya,...,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Ya,Ya,Ya,Pedesaan,Sebagian
87,2,L,NORMAL,Tidak,Ya,Tidak,Tidak,Tidak,Semua,Mungkin,...,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Ya,Ya,Ya,Perkotaan,Ya
88,0,L,OBESITAS,Ya,Ya,Ya,Ya,Ya,Semua,Mungkin,...,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Ya,Kadang-kadang,Ya,Perkotaan,Sebagian
89,1,L,NORMAL,Tidak,Tidak,Tidak,Ya,Ya,Semua,Ya,...,Kadang-kadang,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Ya,Ya,Perkotaan,Sebagian
90,2,L,KURUS,Tidak,Ya,Tidak,Tidak,Tidak,Semua,Mungkin,...,Kadang-kadang,Kadang-kadang,Ya,Ya,Ya,Ya,Kadang-kadang,Ya,Pedesaan,Sebagian

In [44]:
#mengubah data kategorik menjadi bentuk int (data yang dalam bentuk tidak/kadang-kadang=0 ya=1)
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['x1'] = label_encoder.fit_transform(df['x1'])
df['x3'] = label_encoder.fit_transform(df['x3'])
df['x4'] = label_encoder.fit_transform(df['x4'])
df['x5'] = label_encoder.fit_transform(df['x5'])
df['x6'] = label_encoder.fit_transform(df['x6'])
df['x7'] = label_encoder.fit_transform(df['x7'])
df['x8'] = label_encoder.fit_transform(df['x8'])
df['x11'] = label_encoder.fit_transform(df['x11'])
df['x12'] = label_encoder.fit_transform(df['x12'])
df['x13'] = label_encoder.fit_transform(df['x13'])
df['x14'] = label_encoder.fit_transform(df['x14'])
df['x16'] = label_encoder.fit_transform(df['x16'])
df['x17'] = label_encoder.fit_transform(df['x17'])
df['x20'] = label_encoder.fit_transform(df['x20'])
df['x21'] = label_encoder.fit_transform(df['x21'])
df['x22'] = label_encoder.fit_transform(df['x22'])

In [45]:
#mengubah data bertingkat menggunakan replace
df['x2'].replace(['KURUS', 'NORMAL', 'GEMUK', 'OBESITAS'], [0, 1, 2, 3], inplace=True)
df['x9'].replace(['Tidak', 'Mungkin', 'Ya'], [0, 1, 2], inplace=True)
df['x10'].replace(['KURANG DARI 5 JAM', 'ANTARA 5 - 10 JAM', ' LEBIH DARI 10 JAM'], [0, 1, 2], inplace=True)
df['x15'].replace(['Tidak', 'Kadang-kadang', 'Ya'], [0, 1, 2], inplace=True)
df['x18'].replace(['Tidak', 'Kadang-kadang', 'Ya'], [0, 1, 2], inplace=True)
df['x19'].replace(['Tidak', 'Kadang-kadang', 'Ya'], [0, 1, 2], inplace=True)
df['x22'].replace(['Tidak', 'Sebagian', 'Ya'], [0, 1, 2], inplace=True)
df.head()

,class,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22
0,0,1,1,0,0,0,1,1,1,1,...,0,0,2,1,1,0,1,1,0,0
1,2,0,2,1,0,0,0,0,1,1,...,0,0,0,1,1,2,2,1,1,2
2,2,1,1,1,0,0,0,0,1,2,...,0,0,2,1,1,2,2,1,1,0
3,2,1,1,0,1,0,0,0,1,1,...,0,1,2,1,1,2,1,1,1,2
4,0,1,1,0,1,1,1,1,1,2,...,0,0,2,1,1,1,2,1,1,0

In [46]:
data = pd.DataFrame(df)
for column in df.columns:
    data[column] = data[column].astype(float)

print (data)

    class   x1   x2   x3   x4   x5   x6   x7   x8   x9  ...  x13  x14  x15  \
0     0.0  1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  ...  0.0  0.0  2.0
1     2.0  0.0  2.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  ...  0.0  0.0  0.0
2     2.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  2.0  ...  0.0  0.0  2.0
3     2.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  ...  0.0  1.0  2.0
4     0.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  2.0  ...  0.0  0.0  2.0
..    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
86    1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  2.0  ...  0.0  0.0  2.0
87    2.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  ...  0.0  0.0  2.0
88    0.0  0.0  3.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  0.0  0.0  2.0
89    1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  2.0  ...  0.0  0.0  1.0
90    2.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  ...  0.0  0.0  2.0

    x16  x17  x18  x19  x20  x21  x22
0   1.0  1.0  0.0  1.0  1.0  0.0  0.0
1   1.0  1.0  2.0  2.0  1.0  1.0  2.0
2   1.0  1.0  2.0  2.0  1.0  1.0  0.0
3   1.0  1.0  2.0  1.0  1.0  1.0  2.0
4   1.0  1.0  1.0  2.0  1.0  1.0  0.0
..  ...  ...  ...  ...  ...  ...  ...
86  1.0  1.0  2.0  2.0  1.0  0.0  0.0
87  1.0  1.0  2.0  2.0  1.0  1.0  2.0
88  1.0  1.0  2.0  1.0  1.0  1.0  0.0
89  1.0  1.0  2.0  2.0  1.0  1.0  0.0
90  1.0  1.0  2.0  1.0  1.0  0.0  0.0

[91 rows x 23 columns]

In [47]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()
df.iloc[:, 1:] = encoder.fit_transform(df.iloc[:, 1:])

In [48]:
x=df.drop('class', axis=1)
y=df['class']

In [49]:
#melakukan splitting data menggunakan perbandingan 3:7
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

In [56]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(x_train, y_train)

In [59]:
from sklearn.model_selection import cross_val_score
from statistics import mean
scores = cross_val_score(clf, x_test, y_test, cv=10)
print(mean(scores))

0.6166666666666667

In [55]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_validate,cross_val_score
model=GaussianNB()
model.fit(x_train, y_train)
cv_score1=cross_validate(model,x,y,cv=10, return_train_score=True)
cv_score2=cross_val_score(model,x,y,cv=10)
print (cv_score1['train_score'].mean(), cv_score1['test_score'].mean())
print(cv_score2.mean()) #test_score

0.5823998795543511 0.45111111111111113
0.45111111111111113

In [53]:
#Tuning Hyperparameter
from sklearn.model_selection import RepeatedStratifiedKFold
cv_method = RepeatedStratifiedKFold(n_splits=10,  n_repeats=3, random_state=10)
param_grid_nb = {'var_smoothing': np.logspace(0,-9, num=100)}

from sklearn.model_selection import GridSearchCV
gs_NB = GridSearchCV(estimator=model, param_grid=param_grid_nb, cv=cv_method,verbose=1,scoring='accuracy')
gs_NB.fit(x,y)
print(gs_NB.best_params_,gs_NB.best_score_)

Fitting 30 folds for each of 100 candidates, totalling 3000 fits
{'var_smoothing': 0.533669923120631} 0.8496296296296297

In [54]:
from sklearn.naive_bayes import CategoricalNB
from sklearn.model_selection import cross_validate,cross_val_score
model=CategoricalNB()
cv_score1=cross_validate(model,x,y,cv=10, return_train_score=True)
cv_score2=cross_val_score(model,x,y,cv=10)
print (cv_score1['train_score'].mean(), cv_score1['test_score'].mean())
print(cv_score2.mean()) #test_score

0.9755796446853356 0.8566666666666667
0.8566666666666667